# Generated by Django 3.1.6 on 2021-02-04 14:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icdmainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICDCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryCode', models.TextField(default='')),
                ('diagnosisCode', models.IntegerField(unique=True)),
                ('fullCode', models.TextField(default='')),
                ('abbrDesc', models.TextField(default='')),
                ('fullDesc', models.TextField(default='')),
                ('categoryTitle', models.TextField(default='')),
                ('appVersion', models.IntegerField(default=9)),
            ],
        ),
        migrations.AlterField(
            model_name='icdversion',
            name='version',
            field=models.IntegerField(default=1, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100000)]),
        ),
    ]
