# Generated by Django 3.1.6 on 2021-02-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icdmainapp', '0002_auto_20210204_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icdcode',
            name='diagnosisCode',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='icdcode',
            unique_together={('appVersion', 'diagnosisCode')},
        ),
    ]
